# Generated by Django 2.2.7 on 2019-11-23 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gokruze_revenue_tool_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_dump',
            name='Data_Dump_Route_Code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gokruze_revenue_tool_app.Routes_Master'),
        ),
        migrations.AlterField(
            model_name='routes_master',
            name='Routes_Master_Route_Code',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
